### PR TITLE
Apply content_languages to email digests

### PR DESCRIPTION
**Pull request by kgmt0**
I haven't tested this, so I'm not sure if it works.

### CODE REVIEW

**Comment by CIVITAS-John** [comment]
Appreciated. Have you seen my comment on your translator contribution?

**Comment by kgmt0** [comment]
> Appreciated. Have you seen my comment on your translator contribution?

I'm not sure I did. Is it on GitHub or somewhere else?

**Comment by CIVITAS-John** [comment]
https://github.com/NetLogo-Mobile/discourse-translator/pull/1

I replied to this thread.

**Comment by kgmt0** [comment]
>[NetLogo-Mobile/discourse-translator#1](https://github.com/NetLogo-Mobile/discourse-translator/pull/1)
>
>I replied to this thread.

Oh. I saw that one.

**Pull request merged**
